[#18] Declare kotlin-stdlib version explicitly.
Without doing this the publishing plugin wont generate
a valid <dependency> tag inside the generated pom.xml. The
<version> tag will be missing. This however prevents correct
resolution of the dependency, causing the library to fail running with
a NoClassDefFoundError.